# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/es89/Dropbox/Projects/Python/MBC PEMOHT/ui/addIncident.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(366, 501)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 348, 355))
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.serialNumberEdit = QtWidgets.QLineEdit(self.page)
        self.serialNumberEdit.setObjectName("serialNumberEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.serialNumberEdit)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.dateCreationEdit = QtWidgets.QDateEdit(self.page)
        self.dateCreationEdit.setObjectName("dateCreationEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dateCreationEdit)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.ipEdit = QtWidgets.QLineEdit(self.page)
        self.ipEdit.setEnabled(False)
        self.ipEdit.setObjectName("ipEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.ipEdit)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.netmaskEdit = QtWidgets.QLineEdit(self.page)
        self.netmaskEdit.setEnabled(False)
        self.netmaskEdit.setObjectName("netmaskEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.netmaskEdit)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.gatewayEdit = QtWidgets.QLineEdit(self.page)
        self.gatewayEdit.setEnabled(False)
        self.gatewayEdit.setObjectName("gatewayEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.gatewayEdit)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.comEdit = QtWidgets.QSpinBox(self.page)
        self.comEdit.setEnabled(False)
        self.comEdit.setObjectName("comEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.comEdit)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.typeDevicesLayout = QtWidgets.QVBoxLayout()
        self.typeDevicesLayout.setObjectName("typeDevicesLayout")
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.typeDevicesLayout)
        self.locationComboBox = QtWidgets.QComboBox(self.page)
        self.locationComboBox.setObjectName("locationComboBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.locationComboBox)
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 348, 355))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.typicalProblemsLayout = QtWidgets.QVBoxLayout()
        self.typicalProblemsLayout.setObjectName("typicalProblemsLayout")
        self.verticalLayout_4.addLayout(self.typicalProblemsLayout)
        self.moreButton = QtWidgets.QPushButton(self.page_2)
        self.moreButton.setCheckable(True)
        self.moreButton.setObjectName("moreButton")
        self.verticalLayout_4.addWidget(self.moreButton)
        self.commentEdit = QtWidgets.QTextBrowser(self.page_2)
        self.commentEdit.setEnabled(False)
        self.commentEdit.setObjectName("commentEdit")
        self.verticalLayout_4.addWidget(self.commentEdit)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 257, 253))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.brigadeLayout = QtWidgets.QVBoxLayout()
        self.brigadeLayout.setObjectName("brigadeLayout")
        self.verticalLayout_3.addLayout(self.brigadeLayout)
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.desiredFinishDateCalendar = QtWidgets.QCalendarWidget(self.page_3)
        self.desiredFinishDateCalendar.setObjectName("desiredFinishDateCalendar")
        self.verticalLayout_3.addWidget(self.desiredFinishDateCalendar)
        self.toolBox.addItem(self.page_3, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.serialNumberEdit, self.dateCreationEdit)
        Dialog.setTabOrder(self.dateCreationEdit, self.ipEdit)
        Dialog.setTabOrder(self.ipEdit, self.netmaskEdit)
        Dialog.setTabOrder(self.netmaskEdit, self.gatewayEdit)
        Dialog.setTabOrder(self.gatewayEdit, self.comEdit)
        Dialog.setTabOrder(self.comEdit, self.locationComboBox)
        Dialog.setTabOrder(self.locationComboBox, self.commentEdit)
        Dialog.setTabOrder(self.commentEdit, self.desiredFinishDateCalendar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Серийный номер"))
        self.label_2.setText(_translate("Dialog", "Дата заявки"))
        self.label_3.setText(_translate("Dialog", "IP адрес"))
        self.label_4.setText(_translate("Dialog", "Маска подсети"))
        self.label_5.setText(_translate("Dialog", "Адрес шлюза"))
        self.label_6.setText(_translate("Dialog", "Номер COM-порта"))
        self.label_9.setText(_translate("Dialog", "Район установки"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Инфо о комплексе"))
        self.moreButton.setText(_translate("Dialog", "Дополнительно"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Dialog", "Описание проблемы"))
        self.label_7.setText(_translate("Dialog", "Демонтировал инженер:"))
        self.label_8.setText(_translate("Dialog", "Дата желаемой передачи на монтаж:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Dialog", "Дата ожидаемой установки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

