# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/es89/Dropbox/Projects/Python/MBC PEMOHT/ui/userAuth.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userAuth(object):
    def setupUi(self, userAuth):
        userAuth.setObjectName("userAuth")
        userAuth.resize(468, 298)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(userAuth.sizePolicy().hasHeightForWidth())
        userAuth.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(userAuth)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralWidget)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 450, 183))
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.userName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userName.sizePolicy().hasHeightForWidth())
        self.userName.setSizePolicy(sizePolicy)
        self.userName.setMinimumSize(QtCore.QSize(300, 0))
        self.userName.setObjectName("userName")
        self.horizontalLayout.addWidget(self.userName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.userPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userPassword.sizePolicy().hasHeightForWidth())
        self.userPassword.setSizePolicy(sizePolicy)
        self.userPassword.setMinimumSize(QtCore.QSize(300, 0))
        self.userPassword.setObjectName("userPassword")
        self.horizontalLayout_2.addWidget(self.userPassword)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 450, 183))
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 450, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dbHost = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbHost.sizePolicy().hasHeightForWidth())
        self.dbHost.setSizePolicy(sizePolicy)
        self.dbHost.setMinimumSize(QtCore.QSize(275, 0))
        self.dbHost.setObjectName("dbHost")
        self.horizontalLayout_3.addWidget(self.dbHost)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dbLogin = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbLogin.sizePolicy().hasHeightForWidth())
        self.dbLogin.setSizePolicy(sizePolicy)
        self.dbLogin.setMinimumSize(QtCore.QSize(275, 0))
        self.dbLogin.setObjectName("dbLogin")
        self.horizontalLayout_4.addWidget(self.dbLogin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.dbPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.dbPassword.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbPassword.sizePolicy().hasHeightForWidth())
        self.dbPassword.setSizePolicy(sizePolicy)
        self.dbPassword.setMinimumSize(QtCore.QSize(275, 0))
        self.dbPassword.setObjectName("dbPassword")
        self.horizontalLayout_5.addWidget(self.dbPassword)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.dbName = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbName.sizePolicy().hasHeightForWidth())
        self.dbName.setSizePolicy(sizePolicy)
        self.dbName.setMinimumSize(QtCore.QSize(275, 0))
        self.dbName.setObjectName("dbName")
        self.horizontalLayout_7.addWidget(self.dbName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.okButton = QtWidgets.QPushButton(self.centralWidget)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)
        userAuth.setCentralWidget(self.centralWidget)

        self.retranslateUi(userAuth)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(userAuth)

    def retranslateUi(self, userAuth):
        _translate = QtCore.QCoreApplication.translate
        userAuth.setWindowTitle(_translate("userAuth", "Авторизация"))
        self.label.setText(_translate("userAuth", "Имя пользователя"))
        self.label_2.setText(_translate("userAuth", "Пароль"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("userAuth", "Авторизация пользователя"))
        self.label_3.setText(_translate("userAuth", "Сервер MySQL"))
        self.label_4.setText(_translate("userAuth", "Имя пользователя БД"))
        self.label_5.setText(_translate("userAuth", "Пароль пользователя БД"))
        self.label_6.setText(_translate("userAuth", "Имя БД"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("userAuth", "Настройки подключения к MySQL"))
        self.okButton.setText(_translate("userAuth", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userAuth = QtWidgets.QMainWindow()
    ui = Ui_userAuth()
    ui.setupUi(userAuth)
    userAuth.show()
    sys.exit(app.exec_())

